### ISSUE TITLE
Cannot create scan: Please modify Inactivity Timeout. It cannot be more than Max Scan Duration

### ISSUE THREAD

**Issue by pierre-carles-shift** [palantir/terraform-provider-tenablesc#148] opened 2024-02-19 16:50 UTC
## What happened?

It looks like creating a scan is broken, it fails with the error:

```
│ Error: failed to create scan: Please modify Inactivity Timeout. It cannot be more than Max Scan Duration.
│ The attribute 'inactivityTimeout' contains the value '43200' which should be an integer from 3600 to 3600.
```
Looking at the API documentation it looks like these are the default values for MaxScanDuration and InactivityTimeout: https://docs.tenable.com/security-center/api/Scan.htm
Inactivity timeout is not configurable through Terraform, it is not even in the API go package: https://github.com/palantir/tenablesc-client/blob/develop/tenablesc/scan.go#L10

It looks like some changes have been made to the API that broke the Terraform provider

## What did you want to happen?

Be able to create a scan

**Comment by arminaaki** [comment] 2024-06-04 20:32
Thank you for reporting, the issue is resolved in the current release.
https://github.com/palantir/terraform-provider-tenablesc/pull/170

**Closed as completed** 2024-06-06 13:38 UTC
